routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Agentes
    Route::delete('agentes/destroy', 'AgentesController@massDestroy')->name('agentes.massDestroy');
    Route::resource('agentes', 'AgentesController');

    // Sedes
    Route::delete('sedes/destroy', 'SedesController@massDestroy')->name('sedes.massDestroy');
    Route::resource('sedes', 'SedesController');

    // Prioridad
    Route::delete('prioridads/destroy', 'PrioridadController@massDestroy')->name('prioridads.massDestroy');
    Route::resource('prioridads', 'PrioridadController');

    // Incidente
    Route::delete('incidentes/destroy', 'IncidenteController@massDestroy')->name('incidentes.massDestroy');
    Route::resource('incidentes', 'IncidenteController');

    // Estado
    Route::delete('estados/destroy', 'EstadoController@massDestroy')->name('estados.massDestroy');
    Route::resource('estados', 'EstadoController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/media', 'TicketsController@storeMedia')->name('tickets.storeMedia');
    Route::post('tickets/ckmedia', 'TicketsController@storeCKEditorImages')->name('tickets.storeCKEditorImages');
    Route::resource('tickets', 'TicketsController');

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::get('user-alerts/read', 'UserAlertsController@read');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Fichas Tecnicas
    Route::delete('fichas-tecnicas/destroy', 'FichasTecnicasController@massDestroy')->name('fichas-tecnicas.massDestroy');
    Route::post('fichas-tecnicas/parse-csv-import', 'FichasTecnicasController@parseCsvImport')->name('fichas-tecnicas.parseCsvImport');
    Route::post('fichas-tecnicas/process-csv-import', 'FichasTecnicasController@processCsvImport')->name('fichas-tecnicas.processCsvImport');
    Route::resource('fichas-tecnicas', 'FichasTecnicasController');

    // Imprimir
    Route::delete('imprimirs/destroy', 'ImprimirController@massDestroy')->name('imprimirs.massDestroy');
    Route::resource('imprimirs', 'ImprimirController');

    // Componentes
    Route::delete('componentes/destroy', 'ComponentesController@massDestroy')->name('componentes.massDestroy');
    Route::post('componentes/parse-csv-import', 'ComponentesController@parseCsvImport')->name('componentes.parseCsvImport');
    Route::post('componentes/process-csv-import', 'ComponentesController@processCsvImport')->name('componentes.processCsvImport');
    Route::resource('componentes', 'ComponentesController');

    // Imprimirmto
    Route::delete('imprimirmtos/destroy', 'ImprimirmtoController@massDestroy')->name('imprimirmtos.massDestroy');
    Route::resource('imprimirmtos', 'ImprimirmtoController');

    // Hojas De Vida Mantenimiento
    Route::delete('hojas-de-vida-mantenimientos/destroy', 'HojasDeVidaMantenimientoController@massDestroy')->name('hojas-de-vida-mantenimientos.massDestroy');
    Route::post('hojas-de-vida-mantenimientos/parse-csv-import', 'HojasDeVidaMantenimientoController@parseCsvImport')->name('hojas-de-vida-mantenimientos.parseCsvImport');
    Route::post('hojas-de-vida-mantenimientos/process-csv-import', 'HojasDeVidaMantenimientoController@processCsvImport')->name('hojas-de-vida-mantenimientos.processCsvImport');
    Route::resource('hojas-de-vida-mantenimientos', 'HojasDeVidaMantenimientoController');

    // Empleos
    Route::delete('empleos/destroy', 'EmpleosController@massDestroy')->name('empleos.massDestroy');
    Route::post('empleos/media', 'EmpleosController@storeMedia')->name('empleos.storeMedia');
    Route::post('empleos/ckmedia', 'EmpleosController@storeCKEditorImages')->name('empleos.storeCKEditorImages');
    Route::resource('empleos', 'EmpleosController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Empleo.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Empleo extends Model implements HasMedia
{
    use SoftDeletes;
    use InteractsWithMedia;
    use HasFactory;

    public $table = 'empleos';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'vacante',
        'icono',
        'descripcion',
        'requisitos',
        'tiempo',
        'empresa',
        'salario',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/EmpleosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyEmpleoRequest;
use App\Http\Requests\StoreEmpleoRequest;
use App\Http\Requests\UpdateEmpleoRequest;
use App\Models\Empleo;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class EmpleosController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('empleo_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $empleos = Empleo::all();

        return view('admin.empleos.index', compact('empleos'));
    }

    public function create()
    {
        abort_if(Gate::denies('empleo_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.empleos.create');
    }

    public function store(StoreEmpleoRequest $request)
    {
        $empleo = Empleo::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $empleo->id]);
        }

        return redirect()->route('admin.empleos.index');
    }

    public function edit(Empleo $empleo)
    {
        abort_if(Gate::denies('empleo_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.empleos.edit', compact('empleo'));
    }

    public function update(UpdateEmpleoRequest $request, Empleo $empleo)
    {
        $empleo->update($request->all());

        return redirect()->route('admin.empleos.index');
    }

    public function show(Empleo $empleo)
    {
        abort_if(Gate::denies('empleo_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.empleos.show', compact('empleo'));
    }

    public function destroy(Empleo $empleo)
    {
        abort_if(Gate::denies('empleo_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $empleo->delete();

        return back();
    }

    public function massDestroy(MassDestroyEmpleoRequest $request)
    {
        Empleo::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('empleo_create') && Gate::denies('empleo_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Empleo();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/empleos/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.empleo.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.empleos.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="vacante">{{ trans('cruds.empleo.fields.vacante') }}</label>
                <input class="form-control {{ $errors->has('vacante') ? 'is-invalid' : '' }}" type="text" name="vacante" id="vacante" value="{{ old('vacante', '') }}">
                @if($errors->has('vacante'))
                    <span class="text-danger">{{ $errors->first('vacante') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.vacante_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="icono">{{ trans('cruds.empleo.fields.icono') }}</label>
                <input class="form-control {{ $errors->has('icono') ? 'is-invalid' : '' }}" type="text" name="icono" id="icono" value="{{ old('icono', '') }}">
                @if($errors->has('icono'))
                    <span class="text-danger">{{ $errors->first('icono') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.icono_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="descripcion">{{ trans('cruds.empleo.fields.descripcion') }}</label>
                <textarea class="form-control {{ $errors->has('descripcion') ? 'is-invalid' : '' }}" name="descripcion" id="descripcion">{{ old('descripcion') }}</textarea>
                @if($errors->has('descripcion'))
                    <span class="text-danger">{{ $errors->first('descripcion') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.descripcion_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="requisitos">{{ trans('cruds.empleo.fields.requisitos') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('requisitos') ? 'is-invalid' : '' }}" name="requisitos" id="requisitos">{!! old('requisitos') !!}</textarea>
                @if($errors->has('requisitos'))
                    <span class="text-danger">{{ $errors->first('requisitos') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.requisitos_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="tiempo">{{ trans('cruds.empleo.fields.tiempo') }}</label>
                <input class="form-control {{ $errors->has('tiempo') ? 'is-invalid' : '' }}" type="text" name="tiempo" id="tiempo" value="{{ old('tiempo', '') }}">
                @if($errors->has('tiempo'))
                    <span class="text-danger">{{ $errors->first('tiempo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.tiempo_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="empresa">{{ trans('cruds.empleo.fields.empresa') }}</label>
                <input class="form-control {{ $errors->has('empresa') ? 'is-invalid' : '' }}" type="text" name="empresa" id="empresa" value="{{ old('empresa', '') }}">
                @if($errors->has('empresa'))
                    <span class="text-danger">{{ $errors->first('empresa') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.empresa_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="salario">{{ trans('cruds.empleo.fields.salario') }}</label>
                <input class="form-control {{ $errors->has('salario') ? 'is-invalid' : '' }}" type="number" name="salario" id="salario" value="{{ old('salario', '') }}" step="0.01">
                @if($errors->has('salario'))
                    <span class="text-danger">{{ $errors->first('salario') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.salario_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{{ route('admin.empleos.storeCKEditorImages') }}', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $empleo->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/empleos/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.empleo.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.empleos.update", [$empleo->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="vacante">{{ trans('cruds.empleo.fields.vacante') }}</label>
                <input class="form-control {{ $errors->has('vacante') ? 'is-invalid' : '' }}" type="text" name="vacante" id="vacante" value="{{ old('vacante', $empleo->vacante) }}">
                @if($errors->has('vacante'))
                    <span class="text-danger">{{ $errors->first('vacante') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.vacante_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="icono">{{ trans('cruds.empleo.fields.icono') }}</label>
                <input class="form-control {{ $errors->has('icono') ? 'is-invalid' : '' }}" type="text" name="icono" id="icono" value="{{ old('icono', $empleo->icono) }}">
                @if($errors->has('icono'))
                    <span class="text-danger">{{ $errors->first('icono') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.icono_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="descripcion">{{ trans('cruds.empleo.fields.descripcion') }}</label>
                <textarea class="form-control {{ $errors->has('descripcion') ? 'is-invalid' : '' }}" name="descripcion" id="descripcion">{{ old('descripcion', $empleo->descripcion) }}</textarea>
                @if($errors->has('descripcion'))
                    <span class="text-danger">{{ $errors->first('descripcion') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.descripcion_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="requisitos">{{ trans('cruds.empleo.fields.requisitos') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('requisitos') ? 'is-invalid' : '' }}" name="requisitos" id="requisitos">{!! old('requisitos', $empleo->requisitos) !!}</textarea>
                @if($errors->has('requisitos'))
                    <span class="text-danger">{{ $errors->first('requisitos') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.requisitos_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="tiempo">{{ trans('cruds.empleo.fields.tiempo') }}</label>
                <input class="form-control {{ $errors->has('tiempo') ? 'is-invalid' : '' }}" type="text" name="tiempo" id="tiempo" value="{{ old('tiempo', $empleo->tiempo) }}">
                @if($errors->has('tiempo'))
                    <span class="text-danger">{{ $errors->first('tiempo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.tiempo_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="empresa">{{ trans('cruds.empleo.fields.empresa') }}</label>
                <input class="form-control {{ $errors->has('empresa') ? 'is-invalid' : '' }}" type="text" name="empresa" id="empresa" value="{{ old('empresa', $empleo->empresa) }}">
                @if($errors->has('empresa'))
                    <span class="text-danger">{{ $errors->first('empresa') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.empresa_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="salario">{{ trans('cruds.empleo.fields.salario') }}</label>
                <input class="form-control {{ $errors->has('salario') ? 'is-invalid' : '' }}" type="number" name="salario" id="salario" value="{{ old('salario', $empleo->salario) }}" step="0.01">
                @if($errors->has('salario'))
                    <span class="text-danger">{{ $errors->first('salario') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.empleo.fields.salario_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{{ route('admin.empleos.storeCKEditorImages') }}', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $empleo->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/empleos/index.blade.php
@extends('layouts.admin')
@section('content')
@can('empleo_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.empleos.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.empleo.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.empleo.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Empleo">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.vacante') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.icono') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.descripcion') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.tiempo') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.empresa') }}
                        </th>
                        <th>
                            {{ trans('cruds.empleo.fields.salario') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($empleos as $key => $empleo)
                        <tr data-entry-id="{{ $empleo->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $empleo->id ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->vacante ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->icono ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->descripcion ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->tiempo ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->empresa ?? '' }}
                            </td>
                            <td>
                                {{ $empleo->salario ?? '' }}
                            </td>
                            <td>
                                @can('empleo_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.empleos.show', $empleo->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('empleo_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.empleos.edit', $empleo->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('empleo_delete')
                                    <form action="{{ route('admin.empleos.destroy', $empleo->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('empleo_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.empleos.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'asc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Empleo:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection