routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Agentes
    Route::delete('agentes/destroy', 'AgentesController@massDestroy')->name('agentes.massDestroy');
    Route::resource('agentes', 'AgentesController');

    // Sedes
    Route::delete('sedes/destroy', 'SedesController@massDestroy')->name('sedes.massDestroy');
    Route::resource('sedes', 'SedesController');

    // Prioridad
    Route::delete('prioridads/destroy', 'PrioridadController@massDestroy')->name('prioridads.massDestroy');
    Route::resource('prioridads', 'PrioridadController');

    // Incidente
    Route::delete('incidentes/destroy', 'IncidenteController@massDestroy')->name('incidentes.massDestroy');
    Route::resource('incidentes', 'IncidenteController');

    // Estado
    Route::delete('estados/destroy', 'EstadoController@massDestroy')->name('estados.massDestroy');
    Route::resource('estados', 'EstadoController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/media', 'TicketsController@storeMedia')->name('tickets.storeMedia');
    Route::post('tickets/ckmedia', 'TicketsController@storeCKEditorImages')->name('tickets.storeCKEditorImages');
    Route::resource('tickets', 'TicketsController');

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::get('user-alerts/read', 'UserAlertsController@read');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Fichas Tecnicas
    Route::delete('fichas-tecnicas/destroy', 'FichasTecnicasController@massDestroy')->name('fichas-tecnicas.massDestroy');
    Route::post('fichas-tecnicas/parse-csv-import', 'FichasTecnicasController@parseCsvImport')->name('fichas-tecnicas.parseCsvImport');
    Route::post('fichas-tecnicas/process-csv-import', 'FichasTecnicasController@processCsvImport')->name('fichas-tecnicas.processCsvImport');
    Route::resource('fichas-tecnicas', 'FichasTecnicasController');

    // Imprimir
    Route::delete('imprimirs/destroy', 'ImprimirController@massDestroy')->name('imprimirs.massDestroy');
    Route::resource('imprimirs', 'ImprimirController');

    // Componentes
    Route::delete('componentes/destroy', 'ComponentesController@massDestroy')->name('componentes.massDestroy');
    Route::post('componentes/parse-csv-import', 'ComponentesController@parseCsvImport')->name('componentes.parseCsvImport');
    Route::post('componentes/process-csv-import', 'ComponentesController@processCsvImport')->name('componentes.processCsvImport');
    Route::resource('componentes', 'ComponentesController');

    // Imprimirmto
    Route::delete('imprimirmtos/destroy', 'ImprimirmtoController@massDestroy')->name('imprimirmtos.massDestroy');
    Route::resource('imprimirmtos', 'ImprimirmtoController');

    // Hojas De Vida Mantenimiento
    Route::delete('hojas-de-vida-mantenimientos/destroy', 'HojasDeVidaMantenimientoController@massDestroy')->name('hojas-de-vida-mantenimientos.massDestroy');
    Route::post('hojas-de-vida-mantenimientos/parse-csv-import', 'HojasDeVidaMantenimientoController@parseCsvImport')->name('hojas-de-vida-mantenimientos.parseCsvImport');
    Route::post('hojas-de-vida-mantenimientos/process-csv-import', 'HojasDeVidaMantenimientoController@processCsvImport')->name('hojas-de-vida-mantenimientos.processCsvImport');
    Route::resource('hojas-de-vida-mantenimientos', 'HojasDeVidaMantenimientoController');

    // Empleos
    Route::delete('empleos/destroy', 'EmpleosController@massDestroy')->name('empleos.massDestroy');
    Route::post('empleos/media', 'EmpleosController@storeMedia')->name('empleos.storeMedia');
    Route::post('empleos/ckmedia', 'EmpleosController@storeCKEditorImages')->name('empleos.storeCKEditorImages');
    Route::resource('empleos', 'EmpleosController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Componente.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Componente extends Model
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use Auditable;
    use HasFactory;

    public $table = 'componentes';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nombre_del_activo',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/ComponentesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyComponenteRequest;
use App\Http\Requests\StoreComponenteRequest;
use App\Http\Requests\UpdateComponenteRequest;
use App\Models\Componente;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ComponentesController extends Controller
{
    use CsvImportTrait;

    public function index()
    {
        abort_if(Gate::denies('componente_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $componentes = Componente::with(['created_by'])->get();

        return view('admin.componentes.index', compact('componentes'));
    }

    public function create()
    {
        abort_if(Gate::denies('componente_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.componentes.create');
    }

    public function store(StoreComponenteRequest $request)
    {
        $componente = Componente::create($request->all());

        return redirect()->route('admin.componentes.index');
    }

    public function edit(Componente $componente)
    {
        abort_if(Gate::denies('componente_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $componente->load('created_by');

        return view('admin.componentes.edit', compact('componente'));
    }

    public function update(UpdateComponenteRequest $request, Componente $componente)
    {
        $componente->update($request->all());

        return redirect()->route('admin.componentes.index');
    }

    public function show(Componente $componente)
    {
        abort_if(Gate::denies('componente_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $componente->load('created_by');

        return view('admin.componentes.show', compact('componente'));
    }

    public function destroy(Componente $componente)
    {
        abort_if(Gate::denies('componente_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $componente->delete();

        return back();
    }

    public function massDestroy(MassDestroyComponenteRequest $request)
    {
        Componente::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/componentes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.componente.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.componentes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="nombre_del_activo">{{ trans('cruds.componente.fields.nombre_del_activo') }}</label>
                <input class="form-control {{ $errors->has('nombre_del_activo') ? 'is-invalid' : '' }}" type="text" name="nombre_del_activo" id="nombre_del_activo" value="{{ old('nombre_del_activo', '') }}" required>
                @if($errors->has('nombre_del_activo'))
                    <span class="text-danger">{{ $errors->first('nombre_del_activo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.componente.fields.nombre_del_activo_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/componentes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.componente.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.componentes.update", [$componente->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="nombre_del_activo">{{ trans('cruds.componente.fields.nombre_del_activo') }}</label>
                <input class="form-control {{ $errors->has('nombre_del_activo') ? 'is-invalid' : '' }}" type="text" name="nombre_del_activo" id="nombre_del_activo" value="{{ old('nombre_del_activo', $componente->nombre_del_activo) }}" required>
                @if($errors->has('nombre_del_activo'))
                    <span class="text-danger">{{ $errors->first('nombre_del_activo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.componente.fields.nombre_del_activo_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/componentes/index.blade.php
@extends('layouts.admin')
@section('content')
@can('componente_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.componentes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.componente.title_singular') }}
            </a>
            <button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            @include('csvImport.modal', ['model' => 'Componente', 'route' => 'admin.componentes.parseCsvImport'])
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.componente.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Componente">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.componente.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.componente.fields.nombre_del_activo') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($componentes as $key => $componente)
                        <tr data-entry-id="{{ $componente->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $componente->id ?? '' }}
                            </td>
                            <td>
                                {{ $componente->nombre_del_activo ?? '' }}
                            </td>
                            <td>
                                @can('componente_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.componentes.show', $componente->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('componente_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.componentes.edit', $componente->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('componente_delete')
                                    <form action="{{ route('admin.componentes.destroy', $componente->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('componente_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.componentes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Componente:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/componentes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.componente.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.componentes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.componente.fields.id') }}
                        </th>
                        <td>
                            {{ $componente->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.componente.fields.nombre_del_activo') }}
                        </th>
                        <td>
                            {{ $componente->nombre_del_activo }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.componentes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection