routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Audit Logs
    Route::resource('audit-logs', 'AuditLogsController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);

    // Agentes
    Route::delete('agentes/destroy', 'AgentesController@massDestroy')->name('agentes.massDestroy');
    Route::resource('agentes', 'AgentesController');

    // Sedes
    Route::delete('sedes/destroy', 'SedesController@massDestroy')->name('sedes.massDestroy');
    Route::resource('sedes', 'SedesController');

    // Prioridad
    Route::delete('prioridads/destroy', 'PrioridadController@massDestroy')->name('prioridads.massDestroy');
    Route::resource('prioridads', 'PrioridadController');

    // Incidente
    Route::delete('incidentes/destroy', 'IncidenteController@massDestroy')->name('incidentes.massDestroy');
    Route::resource('incidentes', 'IncidenteController');

    // Estado
    Route::delete('estados/destroy', 'EstadoController@massDestroy')->name('estados.massDestroy');
    Route::resource('estados', 'EstadoController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/media', 'TicketsController@storeMedia')->name('tickets.storeMedia');
    Route::post('tickets/ckmedia', 'TicketsController@storeCKEditorImages')->name('tickets.storeCKEditorImages');
    Route::resource('tickets', 'TicketsController');

    // User Alerts
    Route::delete('user-alerts/destroy', 'UserAlertsController@massDestroy')->name('user-alerts.massDestroy');
    Route::get('user-alerts/read', 'UserAlertsController@read');
    Route::resource('user-alerts', 'UserAlertsController', ['except' => ['edit', 'update']]);

    // Fichas Tecnicas
    Route::delete('fichas-tecnicas/destroy', 'FichasTecnicasController@massDestroy')->name('fichas-tecnicas.massDestroy');
    Route::post('fichas-tecnicas/parse-csv-import', 'FichasTecnicasController@parseCsvImport')->name('fichas-tecnicas.parseCsvImport');
    Route::post('fichas-tecnicas/process-csv-import', 'FichasTecnicasController@processCsvImport')->name('fichas-tecnicas.processCsvImport');
    Route::resource('fichas-tecnicas', 'FichasTecnicasController');

    // Imprimir
    Route::delete('imprimirs/destroy', 'ImprimirController@massDestroy')->name('imprimirs.massDestroy');
    Route::resource('imprimirs', 'ImprimirController');

    // Componentes
    Route::delete('componentes/destroy', 'ComponentesController@massDestroy')->name('componentes.massDestroy');
    Route::post('componentes/parse-csv-import', 'ComponentesController@parseCsvImport')->name('componentes.parseCsvImport');
    Route::post('componentes/process-csv-import', 'ComponentesController@processCsvImport')->name('componentes.processCsvImport');
    Route::resource('componentes', 'ComponentesController');

    // Imprimirmto
    Route::delete('imprimirmtos/destroy', 'ImprimirmtoController@massDestroy')->name('imprimirmtos.massDestroy');
    Route::resource('imprimirmtos', 'ImprimirmtoController');

    // Hojas De Vida Mantenimiento
    Route::delete('hojas-de-vida-mantenimientos/destroy', 'HojasDeVidaMantenimientoController@massDestroy')->name('hojas-de-vida-mantenimientos.massDestroy');
    Route::post('hojas-de-vida-mantenimientos/parse-csv-import', 'HojasDeVidaMantenimientoController@parseCsvImport')->name('hojas-de-vida-mantenimientos.parseCsvImport');
    Route::post('hojas-de-vida-mantenimientos/process-csv-import', 'HojasDeVidaMantenimientoController@processCsvImport')->name('hojas-de-vida-mantenimientos.processCsvImport');
    Route::resource('hojas-de-vida-mantenimientos', 'HojasDeVidaMantenimientoController');

    // Empleos
    Route::delete('empleos/destroy', 'EmpleosController@massDestroy')->name('empleos.massDestroy');
    Route::post('empleos/media', 'EmpleosController@storeMedia')->name('empleos.storeMedia');
    Route::post('empleos/ckmedia', 'EmpleosController@storeCKEditorImages')->name('empleos.storeCKEditorImages');
    Route::resource('empleos', 'EmpleosController');

    Route::get('global-search', 'GlobalSearchController@search')->name('globalSearch');
    Route::get('messenger', 'MessengerController@index')->name('messenger.index');
    Route::get('messenger/create', 'MessengerController@createTopic')->name('messenger.createTopic');
    Route::post('messenger', 'MessengerController@storeTopic')->name('messenger.storeTopic');
    Route::get('messenger/inbox', 'MessengerController@showInbox')->name('messenger.showInbox');
    Route::get('messenger/outbox', 'MessengerController@showOutbox')->name('messenger.showOutbox');
    Route::get('messenger/{topic}', 'MessengerController@showMessages')->name('messenger.showMessages');
    Route::delete('messenger/{topic}', 'MessengerController@destroyTopic')->name('messenger.destroyTopic');
    Route::post('messenger/{topic}/reply', 'MessengerController@replyToTopic')->name('messenger.reply');
    Route::get('messenger/{topic}/reply', 'MessengerController@showReply')->name('messenger.showReply');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Ticket.php
<?php

namespace App\Models;

use \DateTimeInterface;
use App\Traits\Auditable;
use App\Traits\MultiTenantModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Ticket extends Model implements HasMedia
{
    use SoftDeletes;
    use MultiTenantModelTrait;
    use InteractsWithMedia;
    use Auditable;
    use HasFactory;

    public $table = 'tickets';

    protected $appends = [
        'adjuntar_archivo',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'nombre',
        'correo',
        'id_incidente_id',
        'id_prioridad_id',
        'id_sede_id',
        'comentenos_mas_sobre_su_incidencia',
        'id_estado_id',
        'id_asignado_id',
        'created_at',
        'updated_at',
        'deleted_at',
        'created_by_id',
    ];

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }

    public function id_incidente()
    {
        return $this->belongsTo(Incidente::class, 'id_incidente_id');
    }

    public function id_prioridad()
    {
        return $this->belongsTo(Prioridad::class, 'id_prioridad_id');
    }

    public function id_sede()
    {
        return $this->belongsTo(Sede::class, 'id_sede_id');
    }

    public function getAdjuntarArchivoAttribute()
    {
        return $this->getMedia('adjuntar_archivo')->last();
    }

    public function id_estado()
    {
        return $this->belongsTo(Estado::class, 'id_estado_id');
    }

    public function id_asignado()
    {
        return $this->belongsTo(Agente::class, 'id_asignado_id');
    }

    public function created_by()
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/TicketsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyTicketRequest;
use App\Http\Requests\StoreTicketRequest;
use App\Http\Requests\UpdateTicketRequest;
use App\Models\Agente;
use App\Models\Estado;
use App\Models\Incidente;
use App\Models\Prioridad;
use App\Models\Sede;
use App\Models\Ticket;
use App\Models\User;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Yajra\DataTables\Facades\DataTables;

class TicketsController extends Controller
{
    use MediaUploadingTrait;

    public function index(Request $request)
    {
        abort_if(Gate::denies('ticket_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if ($request->ajax()) {
            $query = Ticket::with(['id_incidente', 'id_prioridad', 'id_sede', 'id_estado', 'id_asignado', 'created_by'])->select(sprintf('%s.*', (new Ticket())->table));
            $table = Datatables::of($query);

            $table->addColumn('placeholder', '&nbsp;');
            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = 'ticket_show';
                $editGate = 'ticket_edit';
                $deleteGate = 'ticket_delete';
                $crudRoutePart = 'tickets';

                return view('partials.datatablesActions', compact(
                'viewGate',
                'editGate',
                'deleteGate',
                'crudRoutePart',
                'row'
            ));
            });

            $table->editColumn('nombre', function ($row) {
                return $row->nombre ? $row->nombre : '';
            });
            $table->editColumn('correo', function ($row) {
                return $row->correo ? $row->correo : '';
            });
            $table->addColumn('id_incidente_tipo_de_incidente', function ($row) {
                return $row->id_incidente ? $row->id_incidente->tipo_de_incidente : '';
            });

            $table->addColumn('id_prioridad_tipo_de_prioridad', function ($row) {
                return $row->id_prioridad ? $row->id_prioridad->tipo_de_prioridad : '';
            });

            $table->addColumn('id_sede_sede', function ($row) {
                return $row->id_sede ? $row->id_sede->sede : '';
            });

            $table->editColumn('adjuntar_archivo', function ($row) {
                return $row->adjuntar_archivo ? '<a href="' . $row->adjuntar_archivo->getUrl() . '" target="_blank">' . trans('global.downloadFile') . '</a>' : '';
            });
            $table->addColumn('id_estado_estado', function ($row) {
                return $row->id_estado ? $row->id_estado->estado : '';
            });

            $table->addColumn('id_asignado_nombre', function ($row) {
                return $row->id_asignado ? $row->id_asignado->nombre : '';
            });

            $table->editColumn('id_asignado.correo', function ($row) {
                return $row->id_asignado ? (is_string($row->id_asignado) ? $row->id_asignado : $row->id_asignado->correo) : '';
            });

            $table->rawColumns(['actions', 'placeholder', 'id_incidente', 'id_prioridad', 'id_sede', 'adjuntar_archivo', 'id_estado', 'id_asignado']);

            return $table->make(true);
        }

        $incidentes = Incidente::get();
        $prioridads = Prioridad::get();
        $sedes      = Sede::get();
        $estados    = Estado::get();
        $agentes    = Agente::get();
        $users      = User::get();

        return view('admin.tickets.index', compact('incidentes', 'prioridads', 'sedes', 'estados', 'agentes', 'users'));
    }

    public function create()
    {
        abort_if(Gate::denies('ticket_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $id_incidentes = Incidente::pluck('tipo_de_incidente', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_prioridads = Prioridad::pluck('tipo_de_prioridad', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_sedes = Sede::pluck('sede', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_estados = Estado::pluck('estado', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.tickets.create', compact('id_incidentes', 'id_prioridads', 'id_sedes', 'id_estados'));
    }

    public function store(StoreTicketRequest $request)
    {
        $ticket = Ticket::create($request->all());

        if ($request->input('adjuntar_archivo', false)) {
            $ticket->addMedia(storage_path('tmp/uploads/' . basename($request->input('adjuntar_archivo'))))->toMediaCollection('adjuntar_archivo');
        }

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $ticket->id]);
        }

        return redirect()->route('admin.tickets.index');
    }

    public function edit(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $id_incidentes = Incidente::pluck('tipo_de_incidente', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_prioridads = Prioridad::pluck('tipo_de_prioridad', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_sedes = Sede::pluck('sede', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_estados = Estado::pluck('estado', 'id')->prepend(trans('global.pleaseSelect'), '');

        $id_asignados = Agente::pluck('nombre', 'id')->prepend(trans('global.pleaseSelect'), '');

        $ticket->load('id_incidente', 'id_prioridad', 'id_sede', 'id_estado', 'id_asignado', 'created_by');

        return view('admin.tickets.edit', compact('id_incidentes', 'id_prioridads', 'id_sedes', 'id_estados', 'id_asignados', 'ticket'));
    }

    public function update(UpdateTicketRequest $request, Ticket $ticket)
    {
        $ticket->update($request->all());

        if ($request->input('adjuntar_archivo', false)) {
            if (!$ticket->adjuntar_archivo || $request->input('adjuntar_archivo') !== $ticket->adjuntar_archivo->file_name) {
                if ($ticket->adjuntar_archivo) {
                    $ticket->adjuntar_archivo->delete();
                }
                $ticket->addMedia(storage_path('tmp/uploads/' . basename($request->input('adjuntar_archivo'))))->toMediaCollection('adjuntar_archivo');
            }
        } elseif ($ticket->adjuntar_archivo) {
            $ticket->adjuntar_archivo->delete();
        }

        return redirect()->route('admin.tickets.index');
    }

    public function show(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ticket->load('id_incidente', 'id_prioridad', 'id_sede', 'id_estado', 'id_asignado', 'created_by');

        return view('admin.tickets.show', compact('ticket'));
    }

    public function destroy(Ticket $ticket)
    {
        abort_if(Gate::denies('ticket_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ticket->delete();

        return back();
    }

    public function massDestroy(MassDestroyTicketRequest $request)
    {
        Ticket::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('ticket_create') && Gate::denies('ticket_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Ticket();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/tickets/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.ticket.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.tickets.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="nombre">{{ trans('cruds.ticket.fields.nombre') }}</label>
                <input class="form-control {{ $errors->has('nombre') ? 'is-invalid' : '' }}" type="text" name="nombre" id="nombre" value="{{ old('nombre', '') }}" required>
                @if($errors->has('nombre'))
                    <span class="text-danger">{{ $errors->first('nombre') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.nombre_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="correo">{{ trans('cruds.ticket.fields.correo') }}</label>
                <input class="form-control {{ $errors->has('correo') ? 'is-invalid' : '' }}" type="email" name="correo" id="correo" value="{{ old('correo') }}" required>
                @if($errors->has('correo'))
                    <span class="text-danger">{{ $errors->first('correo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.correo_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="id_incidente_id">{{ trans('cruds.ticket.fields.id_incidente') }}</label>
                <select class="form-control select2 {{ $errors->has('id_incidente') ? 'is-invalid' : '' }}" name="id_incidente_id" id="id_incidente_id" required>
                    @foreach($id_incidentes as $id => $entry)
                        <option value="{{ $id }}" {{ old('id_incidente_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('id_incidente'))
                    <span class="text-danger">{{ $errors->first('id_incidente') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.id_incidente_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="id_prioridad_id">{{ trans('cruds.ticket.fields.id_prioridad') }}</label>
                <select class="form-control select2 {{ $errors->has('id_prioridad') ? 'is-invalid' : '' }}" name="id_prioridad_id" id="id_prioridad_id" required>
                    @foreach($id_prioridads as $id => $entry)
                        <option value="{{ $id }}" {{ old('id_prioridad_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('id_prioridad'))
                    <span class="text-danger">{{ $errors->first('id_prioridad') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.id_prioridad_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="id_sede_id">{{ trans('cruds.ticket.fields.id_sede') }}</label>
                <select class="form-control select2 {{ $errors->has('id_sede') ? 'is-invalid' : '' }}" name="id_sede_id" id="id_sede_id" required>
                    @foreach($id_sedes as $id => $entry)
                        <option value="{{ $id }}" {{ old('id_sede_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('id_sede'))
                    <span class="text-danger">{{ $errors->first('id_sede') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.id_sede_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="comentenos_mas_sobre_su_incidencia">{{ trans('cruds.ticket.fields.comentenos_mas_sobre_su_incidencia') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('comentenos_mas_sobre_su_incidencia') ? 'is-invalid' : '' }}" name="comentenos_mas_sobre_su_incidencia" id="comentenos_mas_sobre_su_incidencia">{!! old('comentenos_mas_sobre_su_incidencia') !!}</textarea>
                @if($errors->has('comentenos_mas_sobre_su_incidencia'))
                    <span class="text-danger">{{ $errors->first('comentenos_mas_sobre_su_incidencia') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.comentenos_mas_sobre_su_incidencia_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="adjuntar_archivo">{{ trans('cruds.ticket.fields.adjuntar_archivo') }}</label>
                <div class="needsclick dropzone {{ $errors->has('adjuntar_archivo') ? 'is-invalid' : '' }}" id="adjuntar_archivo-dropzone">
                </div>
                @if($errors->has('adjuntar_archivo'))
                    <span class="text-danger">{{ $errors->first('adjuntar_archivo') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.adjuntar_archivo_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="id_estado_id">{{ trans('cruds.ticket.fields.id_estado') }}</label>
                <select class="form-control select2 {{ $errors->has('id_estado') ? 'is-invalid' : '' }}" name="id_estado_id" id="id_estado_id">
                    @foreach($id_estados as $id => $entry)
                        <option value="{{ $id }}" {{ old('id_estado_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('id_estado'))
                    <span class="text-danger">{{ $errors->first('id_estado') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.ticket.fields.id_estado_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{{ route('admin.tickets.storeCKEditorImages') }}', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $ticket->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

<script>
    Dropzone.options.adjuntarArchivoDropzone = {
    url: '{{ route('admin.tickets.storeMedia') }}',
    maxFilesize: 1024, // MB
    maxFiles: 1,
    addRemoveLinks: true,
    headers: {
      'X-CSRF-TOKEN': "{{ csrf_token() }}"
    },
    params: {
      size: 1024
    },
    success: function (file, response) {
      $('form').find('input[name="adjuntar_archivo"]').remove()
      $('form').append('<input type="hidden" name="adjuntar_archivo" value="' + response.name + '">')
    },
    removedfile: function (file) {
      file.previewElement.remove()
      if (file.status !== 'error') {
        $('form').find('input[name="adjuntar_archivo"]').remove()
        this.options.maxFiles = this.options.maxFiles + 1
      }
    },
    init: function () {
@if(isset($ticket) && $ticket->adjuntar_archivo)
      var file = {!! json_encode($ticket->adjuntar_archivo) !!}
          this.options.addedfile.call(this, file)
      file.previewElement.classList.add('dz-complete')
      $('form').append('<input type="hidden" name="adjuntar_archivo" value="' + file.file_name + '">')
      this.options.maxFiles = this.options.maxFiles - 1
@endif
    },
     error: function (file, response) {
         if ($.type(response) === 'string') {
             var message = response //dropzone sends it's own error messages in string
         } else {
             var message = response.errors.file
         }
         file.previewElement.classList.add('dz-error')
         _ref = file.previewElement.querySelectorAll('[data-dz-errormessage]')
         _results = []
         for (_i = 0, _len = _ref.length; _i < _len; _i++) {
             node = _ref[_i]
             _results.push(node.textContent = message)
         }

         return _results
     }
}
</script>
@endsection